### ISSUE TITLE
Do you know how to implement the HTTP post? 

### ISSUE THREAD

**Issue by ascend-hgx** [flyrainning/AiThinker_A6#1]
Do you know how to implement the HTTP post? In my A6 always return 302 or 400.Like this:
+CIPRCV:422,HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Mon, 10 Apr 2017 07:46:50 GMT
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Location: http://rd.go.10086.cn/go/redirect.do?x-error-code=000

Thank you.

**Comment by flyrainning** [comment]
I've tried many times to fail, HTTP just not work.
I'm using TCP/UDP now 

看到你的Location信息，我猜你肯定懂中文。用的是中国移动的网络吧。你访问的地址被DNS劫持或者被墙了，访问不到，中国移动自动给你重定向到他们自己的网站了。你可以试试使用国内主机，域名备案，将端口更改成不常用的端口号，或者换联通的网络试试。
另外，我自己用芯片自带的http功能一直没成功，不知道原因，如果可以还是建议直接使用tcp/udp，毕竟http对流量有不少消耗。

**Comment by ascend-hgx** [comment]
我是用我的手机卡做的实验，用的是阿里的共享主机，已经备案了。在浏览器和fiddler抓包软件里都能够正常访问，换到手机卡就不行（TCP能连接上80端口，但是无法执行HTTP请求），不知道哪里出错了。
对了，你说的自带http功能有吗？我是用tcp连接之后tcp发送抓包得到的HTTP请求的

**Comment by flyrainning** [comment]
我说的是芯片自带的HTTP请求功能不能用，芯片手册上有自带HTTP功能，但是我测试很多次都不成功。我是通过TCP直接通讯的，没使用HTTP协议，不过理论上通过TCP自己拼接HTTP头，是可以正常访问的，注意不要漏掉Host字段。你的问题八成就是移动运营商的DNS劫持之类的问题，你试试换联通卡，或者不要通过域名访问，直接通过IP地址，配合HTTP头的Host来访问。

**Comment by ascend-hgx** [comment]
好的，我直接用IP试试，谢啦

**Comment by ascend-hgx** [comment]
刚测试能和服务器通信了，主要问题是在CIPSTATRT的时候就要使用IP地址，而不能用域名；接下来直接用CIPSEND发送HTTP协议就可以了。应该就是你说的DNS被劫持，导致我域名无法正常解析。
